### PR TITLE
adding STARRED PSF fitting notebook

### PR DESCRIPTION
**Pull request by martin-millon**
This adds a new notebook demonstrating how to use the STARRED PSF reconstruction module, within lenstronomy. 
This is not directly comparable with the `time_delay_cosmography_with_uncertain_psf.ipynb` notebook because here, Starred reconstructs the PSF on super-sampled grid. Subsampling the PSF leads to a better accuracy on Ddt, even though this is not really significant. 

Final model with Starred reconstruction (`point_source_supersampling_factor = 3`, `supersampling_factor: 1`):
image

Same config, with iterative PSF reconstruction: 
image

### CODE REVIEW

**Comment by martin-millon** [comment]
<p>Yes, if you turn 'verbose' to False in the kwargs_starred dictionary, STARRED is not printing anything in the terminal. I can make it False by default if needed. </p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/31/discussion/#comment-2142744622'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by martin-millon** [comment]
<p>This is the same thing in the original notebook! Gamma is set to 1.95 in the simulation but the fit converges to 1.99</p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/31/discussion/#comment-2142744656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by martin-millon** [comment]
<p>The DDt is actually more accurate, but I think this is because you subsample the PSF. </p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/31/discussion/#comment-2142744656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by martin-millon** [comment]
<p>And true Fermat potential is not plotted, so I can't tell if this is off or not. Probably not if Ddt is unbiased. </p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/31/discussion/#comment-2142744656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sibirrer** [comment]
<p>ah, we should plot the true Fermat potential (I thought it is outside). I will also do it for the other notebook</p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/31/discussion/#comment-2142744656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sibirrer** [comment]
@martin-millon just checking whether this PR needs edits. If you think it's ready to merge, please ping me

**Comment by martin-millon** [comment]
Yes, this can be merged!

**Comment by sibirrer** [comment]
I left a minor request on the notebook before merging. Can you please address it and then it's good to merge

**Comment by martin-millon** [comment]
This should be fixed in my latest commit.

**Review by sibirrer — APPROVED** [review]
looks great, thank you very much!

**Pull request merged**
