### PR TITLE
Decoupled multi-plane example notebook 

### PR DESCRIPTION
**Pull request by dangilman**
This notebook illustrates how to implement the "decoupled multi-plane" approximation when modeling a quadruply-imaged quasar plus imaging data described in pull request #592 in lenstronomy. This notebook illustrates how to interface with pyhalo to generate population of dark matter line-of-sight halos, inject them in the lens model, interpolate the deflection field they produce and then reconstruct the lens mass and source light. I also perform a few particle swarm iterations for the same substructure population analyzed with exact ray tracing, and find the decoupled multi-plane approach provides an increase in speed by a factor of 1,229.

### CODE REVIEW

**Review by sibirrer — CHANGES_REQUESTED** [review]
Looks really great! I have some minor suggestions on the NB review

**Comment by dangilman** [comment]
<p>sorry, those lines shouldn't be there</p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595328'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595315'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
<p>done. the bits related to the image magnification aren't actually used later on in the notebook so I'll take them out </p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595338'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595351'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
<p>good point! </p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595363'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
<p>added</p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595375'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
<p>that would probably be a good idea moving forward.... </p>

---

 <a href='https://app.reviewnb.com/lenstronomy/lenstronomy-tutorials/pull/26/discussion/#comment-1965595382'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dangilman** [comment]
@sibirrer I updated the notebook to reflect your recent comments, thanks!

**Review by sibirrer — APPROVED** [review]

**Pull request merged**
