### PR TITLE
Feature/readme index

### PR DESCRIPTION
**Pull request by ajshajib**
- Add an tutorial index in the Readme file
 - Rename notebooks to make them more descriptive
 - Link the notebooks from the Readme index (to-do)

### CODE REVIEW

**Comment by sibirrer** [comment]
@ajshajib there seems to be a conflict indicated in this PR. Perhaps you can solve it with the web editor or use the command line

**Comment by ajshajib** [comment]
I tried to solve the conflict, but seems like the solutions only gets saved after merging.

**Comment by sibirrer** [comment]
> I tried to solve the conflict, but seems like the solutions only gets saved after merging.

Are you able to sync your branch on the GitHub interface?

**Comment by ajshajib** [comment]
Btw, are you ok with renaming the *.ipynb files like I did within the lens modeling section? If so, I can do similar renaming to the rest of the notebooks. After that, I can place the appropriate links in the Readme.

**Comment by ajshajib** [comment]
> Are you able to sync your branch on the GitHub interface?

It does nothing if click on the sync button.

**Comment by sibirrer** [comment]
> 

hmm, I don't really like file names with white spaces. Copying links may cause issue and things like that. Was your proposal mainly such that the link names can directly be the links instead of adding a longer document string for the links?

**Comment by sibirrer** [comment]
> > Are you able to sync your branch on the GitHub interface?
> 
> It does nothing if click on the sync button.

It looks to be fixed, no merge conflict indicated anymore

**Comment by ajshajib** [comment]
Ok, my proposal was to make the file names more descriptive, sometimes it can be a little hard to say what's inside the notebook just from the name. How about, we keep the underscores, but allow longer names to put more description.

**Comment by sibirrer** [comment]
> Ok, my proposal was to make the file names more descriptive, sometimes it can be a little hard to say what's inside the notebook just from the name. How about, we keep the underscores, but allow longer names to put more description.

Yes, I like that! Underscores or '-' should be placed/remain between words

**Comment by ajshajib** [comment]
I think, in almost all cases, the title of the notebook inside is a sufficient description. We can just put that title as the notebook name with underscores in place of white spaces. How about that?

**Comment by ajshajib** [comment]
@sibirrer, I have updated all the notebook names. If you find everything ok, please approved the PR. Then, I will put permanent links in the ReadMe and create a second PR.

**Review by sibirrer — APPROVED** [review]
Looks great! Thank you very much!

**Pull request merged**
